### ISSUE TITLE
Feedback for "Using Ignore Lists to Prevent Deployment"

### ISSUE THREAD

**Issue by rangulvers** [SAP-docs/sap-hana-cloud-hana-database#10]
https://help.sap.com/docs/HANA_CLOUD_DATABASE/c2b99f19e9264c4d9ae9221b22f6f589/31a5960f7c4e457ea5ed7d4b2b8f172c.html

There seems to by a typo in the "Note" section. It should be `.hdiignore` and not `-hdiignore`

![image](https://user-images.githubusercontent.com/5235430/219594230-6a7bd9b0-72dd-4f09-b105-85da5c9fa123.png)

Also it is not possible to commit changes to the site. When clicking on "Edit" the following error page is displayed 

![image](https://user-images.githubusercontent.com/5235430/219594148-959fb63e-cc5d-476d-be92-391c20b0104d.png)

**Comment by gn-sap** [comment]
Thanks for picking this up. The issue has been fixed in this (and for all future) versions.

**Comment by gn-sap** [comment]
The issue has been fixed in this (and for all future) versions.

**Comment by rangulvers** [comment]
https://people.sap.com/m.sohns
