### ISSUE TITLE
Feedback for "M_DISK_USAGE System View"

### ISSUE THREAD

**Issue by z49x2vmq** [SAP-docs/sap-hana-cloud-hana-database#11]
https://help.sap.com/docs/HANA_CLOUD_DATABASE/c1d3f60099654ecfb3fe36ac93c121bb/a2aac2ee72b341699fa8eb3988d8cecb.html

Doc only states three columns, 'HOST', 'USAGE_TYPE', 'USED_SIZE'. 
But actual view contain four columns, 'HOST', 'USAGE_TYPE', 'USED_SIZE', and 'FILE_SIZE'

USED_SIZE and FILE_SIZE have exactly same value, at least for my hana cloud instance.

Need to check if FILE_SIZE column is needed. If so doc should be updated. If not, FILE_SIZE column should be removed from the monitoring view.

**Comment by aptk001** [comment]
Hi, thanks for pointing this out. FILE_SIZE and USED_SIZE can be different, so this will be updated in the documentation.
