### ISSUE TITLE
typo  : JSON <table_column...   =>  <JSON_table_column... 

### ISSUE THREAD

**Issue by jinniahn** [SAP-docs/sap-hana-cloud-hana-database#14]
### Issue description

https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/json-table-function-json?q=json_table

```

<JSON_table_regular_column_definition>
Defines the regular columns. Each result (row) of a regular JSON table column is equivalent to a JSON_VALUE function result.

<JSON_table_regular_column_definition> ::= <column_name> <data_type>
 PATH <JSON_table_column_path_specification> 
 [ JSON <table_column_empty_behavior> ON EMPTY ]   
^^^^^^^^^^^^
 [ <JSON_table_column_error_behavior> ON ERROR ]

```

JSON <table_column...   =>  <JSON_table_column... 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

JSON_TABLE Function (JSON)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/json-table-function-json?q=json_table

**Comment by aptk001** [comment]
Thanks for pointing this out. I've fixed the mistake and it will be updated the next time we refresh the documentation.
