### ISSUE TITLE
GENERATED BY DEFAULT RESET BY statement can be improved to allow "NULL" for "RESET BY QUERY"

### ISSUE THREAD

**Issue by jingweiz2017** [SAP-docs/sap-hana-cloud-hana-database#18]
### Issue description

Regarding the syntax of "GENERATED BY DEFAULT RESET BY" statement described in detail in the following link:
https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/create-table-statement-data-definition#loio20d58a5f75191014b2fe92141b7df228__create_table_as_subquery

I have a use case that may suggest for an enhancement. 
I would like to have a way to allow "RESET BY QUERY" to be set NULL in its application in GENERATED BY DEFAULT RESET BY during the table creation. Thus, current sequence can be saved by Hana rather than generated by reset by query during database restart. 

The use case:
We have a table(e.g. table foo) with its records to be moved over to another table(foo_archive) when its job is done. Let's say current value of the id sequence is 7 after some usage. Now, there is not records in table foo as all records have been moved to foo_archive. Now, there happen to be a database restart, the id sequence of the table foo will be reset to 1. However, we want the sequence could resume where it was left which is 7.
 
I know there can be a work around to create a standalone sequence without "reset by query" and assign it to the id column for sequence generation. But, it will be easier if I can specify that in the create table script by one shot, something like:
```
CREATE COLUMN TABLE foo(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (RESET BY NULL),
    PRIMARY KEY(
	    id
    )
);
```
In this way, I could instruct Hana to use the saved sequence when restart rather than getting it from "reset by query".
What do you think?

You may reach me by: rocky.zhang@sap.com in case for any clarification.

Regards,
Rocky

 

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

CREATE TABLE Statement (Data Definition)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/create-table-statement-data-definition

**Comment by aptk001** [comment]
Hi Rocky,

This repository is for feedback on the documentation.

For support and enhancements, see the [SAP Community](https://answers.sap.com/) and [SAP Support Portal](https://support.sap.com/en/index.html).
