### ISSUE TITLE
Typo in docs: PARGUET  should be PARQUET 

### ISSUE THREAD

**Issue by thomashanke** [SAP-docs/sap-hana-cloud-hana-database#19]
### Issue description

See title

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

EXPORT INTO Statement (Data Import Export)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/export-into-statement-data-import-export?locale=en-US&version=2023_4_QRC

**Comment by aptk001** [comment]
Thanks for pointing this out. I've corrected the typo and it will be reflected in the next publication.
