### ISSUE TITLE
JSON_TABLE function - add example with filter

### ISSUE THREAD

**Issue by kaufmanntob** [SAP-docs/sap-hana-cloud-hana-database#23]
### Issue description

Hello!
The documentation of the JSON_TABLE function already contains a good example...

SELECT JT.*

FROM JSON_TABLE(T1.B, '$.LineItems[*]'
COLUMNS
    (
        RN FOR ORDINALITY,
        ITEM_NUMBER INT PATH '$.ItemNumber',
        UPC_CODE BIGINT PATH '$.Part.UPCCode'
    )
) AS JT;

But in this example the whole table T1 is read to get the JSON of column B...

Could you please check and add the following example to the documentation? T1_WITH_FILTER is a pre-query in a WITH-clause. This allows to specify a filter to reduce the rows of table T1.

WITH T1_WITH_FILTER AS
(
      SELECT A, B FROM T1 WHERE A = 1
)

SELECT JT.*
FROM JSON_TABLE(T1_WITH_FILTER, '$.LineItems[*]'
COLUMNS
    (
        RN FOR ORDINALITY,
        ITEM_NUMBER INT PATH '$.ItemNumber',
        UPC_CODE BIGINT PATH '$.Part.UPCCode'
    )
) AS JT;

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

JSON_TABLE Function (JSON)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/HANA_CLOUD_DATABASE/c1d3f60099654ecfb3fe36ac93c121bb/f8f6916b5c434a6fbd1bb7e0dc65acd4.html?q=JSON_table

**Comment by aptk001** [comment]
Hi, thanks for the suggestion. The example has been added and should be visible with the next publish of the documentation.
