### ISSUE TITLE
Column name TOTAL_STATEMENT_ADMIN_COUNT is not correct

### ISSUE THREAD

**Issue by Yoong-Hee** [SAP-docs/sap-hana-cloud-hana-database#25]
M_WORKLOAD_CLASS_STATISTICS System View has TOTAL_STATEMENT_ADMIN_COUNT column according to this document.
https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/m-workload-class-statistics-system-view?q=M_WORKLOAD_CLASS_STATISTICS

But in HANA Cloud system, the correct column name is not TOTAL_STATEMENT_ADMIN_COUNT, but TOTAL_STATEMENT_ADMIT_COUNT.

I'd like you to review and change it.

Thank you.

**Comment by aptk001** [comment]
Hi, thanks for pointing this out. This has been fixed, and the correction will be visible the next time we refresh the documentation.
