### ISSUE TITLE
Contains Predicate Issue

### ISSUE THREAD

**Issue by Munna-Kumar1990** [SAP-docs/sap-hana-cloud-hana-database#29]
### Issue description

CREATE SCHEMA mySchema;
CREATE COLUMN TABLE mySchema.SEARCH_TEXT( Content VARCHAR(20), Descrip VARCHAR(20), Comment VARCHAR(20) );
INSERT INTO mySchema.SEARCH_TEXT VALUES( 'Blue baseball cap', 'Vintage', 'Out of stock');  
INSERT INTO mySchema.SEARCH_TEXT VALUES( 'Red car', 'Vintage', 'Taking orders' );  
INSERT INTO mySchema.SEARCH_TEXT VALUES( 'Bluish sky', 'Retro', 'Discontinued' );

SELECT SCORE() AS SCORE,*  
   FROM mySchema.SEARCH_TEXT  
   WHERE CONTAINS(CONTENT,'cap',FUZZY(0.0))  
   ORDER BY SCORE DESC;

Showing only One Record that contains Red car.
![image](https://github.com/user-attachments/assets/410797ca-8a2d-4073-8676-f42c2b6a51e4)

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

CONTAINS Predicate

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/contains-predicate

**Comment by aptk001** [comment]
Hi, thanks for pointing this out. The example itself is correct, but there is an issue with the fuzzy search. This has been reported.
