### ISSUE TITLE
missed `CREATE COLUMN VIEW`

### ISSUE THREAD

**Issue by kulliax** [SAP-docs/sap-hana-cloud-hana-database#31]
Hi,

While reading the documentation, I came across `CREATE COLUMN VIEW`, eg here: https://help.sap.com/docs/SAP_HANA_PLATFORM/e8e6c8142e60469bb401de5fdb6f7c00/63efa79c963d4243ad2a894e2b5bd10c.html

I can't find anything about this in the docs:

https://github.com/SAP-docs/sap-hana-cloud-hana-database/blob/9a536be2fdba3499a2a6099ac88c5b7595d4ade6/docs/sql-ref/010-SQL-Reference/012-SQL-Statements/create-view-statement-data-definition-20d5fa9.md?plain=1#L14

**Comment by aptk001** [comment]
Hi, thanks for pointing this out. CREATE COLUMN VIEW is a separate statement related to calculation views, but is missing from the documentation. This will be added back in the next time we republish.

**Comment by kulliax** [comment]
Hi @aptk001 

can you give an approximate time frame for a new publication?

SCN: 14806
