### ISSUE TITLE
Provide an example of an updateable view

### ISSUE THREAD

**Issue by kulliax** [SAP-docs/sap-hana-cloud-hana-database#32]
Hi,

The documentation says that a view is updateable under certain conditions. I am trying to set a lock in a view which is based on 2 column tables or 2 views. Unfortunately the create statement, for the join view, always generates `WITH READ ONLY`. 
Please clarify or give an example.

https://github.com/SAP-docs/sap-hana-cloud-hana-database/blob/9a536be2fdba3499a2a6099ac88c5b7595d4ade6/docs/sql-ref/010-SQL-Reference/012-SQL-Statements/create-view-statement-data-definition-20d5fa9.md?plain=1#L623-L645

**Comment by aptk001** [comment]
Hi, the first restriction listed here, "Each column in the view maps to the column of a single table", is meant to say that updates are not supported on a view that points to multiple tables. For example, this view would be read only:

CREATE VIEW view1 AS SELECT table1.ColA, table2.ColB FROM table1, table2;

This will be updated to be more clear about the restriction for the next time we republish. Thanks for bringing this up.
