### ISSUE TITLE
Feedback for "Maintaining Multitarget Application Services in Cloud Foundry"

### ISSUE THREAD

**Issue by quietn** [SAP-docs/sap-hana-cloud-hana-database#6]
https://help.sap.com/docs/HANA_CLOUD_DATABASE/b9902c314aef4afb8f7a29bf8c5b37b3/33e3c5926feb4098a32edcaa7290c3d1.html

There is an instance of "the the" on the page.

**Comment by gn-sap** [comment]
This issue has already been fixed.
