### ISSUE TITLE
Feedback for "Syntax Options in the hdbgrants File"

### ISSUE THREAD

**Issue by martinplangg** [SAP-docs/sap-hana-cloud-hana-database#8]
https://help.sap.com/docs/HANA_CLOUD_DATABASE/c2b99f19e9264c4d9ae9221b22f6f589/f49c1f5c72ee453788bf79f113d83bf9.html

Hi,
In the documentation for schema_roles the definition of the schema itself is missing, e.g. "schema": "MySchemaS1"
best regards
Martin
```
{
  "EPM_XXX-table-grantor": {
   "object_owner": { 
      "schema_roles": [
        {
          "schema": "MySchemaS1",
          "roles" : ["Schema_RoleR1", "Schema_RoleR2"],
          "roles_with_admin_option" : ["Schema_RoleR3", "Schema_RoleR4"]
        }
      ]
    }
  }
}

```

**Comment by gn-sap** [comment]
Thanks for catching this! The Cloud documentation will be updated where appropriate to reflect the on-premise version, which does include the information about the "schema" property.
